pipeline {
    agent any

    environment {
        AZURE_CLIENT_ID = credentials('azure-credentials') // Service Principal App ID
        AZURE_CLIENT_SECRET = credentials('azure-credentials') // Service Principal Password
        AZURE_TENANT_ID = 'af73384e-f91b-4705-b1c6-05fed392027d'
        ACR_NAME = 'golan'
        ACR_REPO_NAME = 'golan-app'
        IMAGE_TAG = 'latest'
        RESOURCE_GROUP = 'dev-opps'
        AKS_CLUSTER_NAME = 'golanapp'
        REPO_URL = 'https://github.com/Mujadid13/golan-app2.git'
        HELM_RELEASE_NAME_GOLAN = 'helm/charts/golan-app'
        HELM_REPO_DIR = '~/my-helm-repo'
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    git branch: 'main', url: "${REPO_URL}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $ACR_NAME.azurecr.io/$ACR_REPO_NAME:$IMAGE_TAG -f app/Dockerfile .'
                }
            }
        }

        stage('Login to ACR') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'azure-credentials', usernameVariable: 'AZURE_CLIENT_ID', passwordVariable: 'AZURE_CLIENT_SECRET')]) {
                        sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID'
                        sh 'az acr login --name $ACR_NAME'
                    }
                }
            }
        }

        stage('Push Docker Image to ACR') {
            steps {
                script {
                    sh 'docker push $ACR_NAME.azurecr.io/$ACR_REPO_NAME:$IMAGE_TAG'
                }
            }
        }

        stage('Configure kubectl') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'azure-credentials', usernameVariable: 'AZURE_CLIENT_ID', passwordVariable: 'AZURE_CLIENT_SECRET')]) {
                        sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID'
                        sh 'az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing'
                    }
                }
            }
        }

        stage('Deploy Redis') {
            steps {
                script {
                    sh 'kubectl apply -f redis/redis-deployment.yaml'
                    sh 'kubectl apply -f redis/redis-service.yaml'
                }
            }
        }

        stage('Package and Configure Helm Repo') {
            steps {
                script {
                    sh '''
                    mkdir -p $HELM_REPO_DIR
                    cd golan-app
                    helm package .
                    mv golan-app-0.1.0.tgz $HELM_REPO_DIR/
                    cd $HELM_REPO_DIR
                    helm repo index .
                    helm repo add golan-app http://localhost:8000
                    helm repo update
                    '''
                }
            }
        }

        stage('Serve Helm Repo Locally') {
            steps {
                script {
                    sh '''
                    cd $HELM_REPO_DIR
                    nohup python3 -m http.server 8000 &
                    '''
                }
            }
        }

        stage('Deploy Golan App with Helm') {
            steps {
                script {
                    sh 'helm upgrade --install golan-app golan-app/golan-app --set image.repository=$ACR_NAME.azurecr.io/$ACR_REPO_NAME --set image.tag=$IMAGE_TAG'
                }
            }
        }

        stage('Debug') {
            steps {
                script {
                    sh 'kubectl get all'
                    sh 'kubectl get events'
                    sh 'kubectl describe pods'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
