# Default values for golan-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replica count for the application
replicaCount: 2  # Set to 2 for redundancy; adjust as needed

# Container image configuration
image:
  repository: golan  # Replace with your actual image repository
  pullPolicy: IfNotPresent  # Pull the image if it's not present locally
  tag: "latest"  # Specify the image tag; adjust as necessary

# Secrets for pulling from a private image repository
imagePullSecrets:
  - name: acr-secret  # Replace with your actual secret name if using a private repo

# Override chart name
nameOverride: ""
fullnameOverride: "golan-app"  # Full name for the application

# Service account configuration
serviceAccount:
  create: true  # Create a service account for the application
  automount: true  # Automatically mount the service account's API credentials
  annotations: {}  # Add any necessary annotations here
  name: ""  # Leave empty to auto-generate name

# Pod annotations for metadata
podAnnotations:
  monitoring.example.com/enabled: "true"  # Enable monitoring
  version: "v1.0"  # Application version

# Pod labels for organization
podLabels: {}

# Pod security context
podSecurityContext:
  fsGroup: 2000  # Group ID for file system access

# Container security context
securityContext:
  runAsUser: 1000  # User ID for running the container
  runAsNonRoot: true  # Ensure the container runs as a non-root user
  capabilities:
    drop:
      - ALL  # Drop all capabilities for security

# Resources for the application
resources:
  limits:
    cpu: "500m"  # Limit CPU usage
    memory: "512Mi"  # Limit memory usage
  requests:
    cpu: "250m"  # Request CPU usage
    memory: "256Mi"  # Request memory usage

# Node selector for scheduling
nodeSelector: {}

# Tolerations for scheduling on tainted nodes
tolerations: []

# Affinity for scheduling preferences
affinity: {}

# Service configuration
service:
  enabled: true  # Enable the service
  name: "golan-app-service"  # Service name
  type: LoadBalancer  # Service type; adjust as necessary (ClusterIP, NodePort, etc.)
  port: 8080  # Service port
  targetPort: 8080  # Port the container listens on
  annotations: {}  # Add any necessary service annotations here

# Redis configuration
redis:
  enabled: true  # Enable Redis
  image:
    repository: redis  # Redis image repository
    tag: "latest"  # Redis image tag
  service:
    type: ClusterIP  # Redis service type
    port: 6379  # Redis service port

# Horizontal Pod Autoscaler configuration
hpa:
  enabled: true  # Enable Horizontal Pod Autoscaler
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  targetCPUUtilizationPercentage: 80  # Target CPU utilization percentage
  targetMemoryUtilizationPercentage: 70

# Ingress configuration
ingress:
  enabled: false

# Health checks configuration
livenessProbe:
  enabled: true  # Enable liveness probe
  initialDelaySeconds: 30  # Delay before the probe starts
  periodSeconds: 10  # Frequency of the probe

readinessProbe:
  enabled: true  # Enable readiness probe
  initialDelaySeconds: 5  # Delay before the probe starts
  periodSeconds: 10  # Frequency of the probe

