apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  type: ClusterIP  # Change to LoadBalancer if external access is needed
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis-server
  selector:
    app: redis-server
